- name: Install dnf-plugin-core
  become: true
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Install flatpak
  become: true
  dnf:
    name: flatpak
    state: latest

- name: Install the 'Development tools' package group
  become: true
  dnf:
    name: '@Development tools'
    state: present

- name: Install packages needed for development
  become: true
  dnf:
    name: "{{ fedora_ansible_packages | map('quote') |list }}"
    state: present