- import_tasks: "{{ role_path }}/tasks/chrome.yml"
  become: true
  tags:
    - base
    - browsers

- name: Install browsers
  become: true
  dnf:
    name: "{{ fedora_browsers | map('quote') | list }}"
    state: latest