- import_tasks: "{{ role_path }}/tasks/docker.yml"
  become: true
  tags:
    - containers
    - base

- import_tasks: "{{ role_path }}/tasks/podman.yml"
  become: true
  tags:
    - containers
    - base

- import_tasks: "{{ role_path }}/tasks/kubernetes.yml"
  become: true
  tags:
    - containers
    - kubernetes
