- name: Install virtualization packages
  tags:
    - base
    - virtualization
  become: true
  dnf:
    name: "{{ fedora_libvirt_packages | map('quote') | list }}"
    state: latest

- name: Install qemu packages
  tags:
    - base
    - virtualization
  become: true
  dnf:
    name: "{{ fedora_qemu_packages | map('quote') | list }}"
    state: latest

- name: Install vmware tools
  tags:
    - base
    - virtualization
  become: true
  dnf:
    name: "{{ fedora_vmware | map('quote') | list }}"
    state: latest

- name: Install hyperv packages
  tags:
    - base
    - virtualization
  become: true
  dnf:
    name: "{{ fedora_hyperv_packages | map('quote') | list }}"
    state: latest

- name: Enable nested virtualization
  tags:
    - base
    - virtualization
  become: true
  shell: |
    modprobe -r kvm_intel
    modprobe kvm_intel nested=1
    if ! grep -q "kvm_intel" /etc/modprobe.d/kvm.conf; then echo "options kvm_intel nested=1" >> /etc/modprobe.d/kvm.conf; fi

- name: Check if nested virtualization is enabled
  become: true
  tags:
    - base
    - virtualization
  shell: |
    cat /etc/modprobe.d/kvm.conf | grep kvm_intel
  register: nested_virt

- name: Fail if nested virtualization didn't get enabled
  fail:
    msg: "Nested virtualization didn't get enabled. Either rerun the playbook with the appropriate tags or enable it manually"
  when: nested_virt.stdout == "options kvm_intel nested=1"
