- name: Install dnf-plugin-core
  become: true
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Enable docker repository
  become: true
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    warn: false
  args: 
    creates: /etc/yum.repos.d/docker-ce.repo 

- name: Importing (free) key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Importing (non-free) key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Enable RPMFusion (free) repository
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: latest

- name: Enable RPMFusion (non-free) repository
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: latest

- name: Install CUDA repository
  become: true
  command:
    cmd: dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64/cuda-fedora35.repo
    warn: false
  args: 
    creates: /etc/yum.repos.d/cuda-fedora35.repo
