- name: Install dnf-plugin-core
  become: true
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Enable docker repository
  become: true
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    warn: false
  args: 
    creates: /etc/yum.repos.d/docker-ce.repo 

- name: Importing (free) key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Importing (non-free) key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Enable RPMFusion (free) repository
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: latest

- name: Enable RPMFusion (non-free) repository
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: latest

- name: Install CUDA repository
  become: true
  command:
    cmd: "dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora{{ ansible_distribution_major_version }}/x86_64/cuda-fedora{{ ansible_distribution_major_version }}.repo"
    warn: false
  args: 
    creates: "/etc/yum.repos.d/cuda-fedora{{ansible_distribution_major_version}}.repo"

- name: Importing NVIDIA machine learning repository key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://developer.download.nvidia.com/compute/machine-learning/repos/rhel8/x86_64/7fa2af80.pub

- name: Install NVIDIA machine learning repository
  become: true
  dnf:
    name: "https://developer.download.nvidia.com/compute/machine-learning/repos/rhel8/x86_64/nvidia-machine-learning-repo-rhel8-1.0.0-1.x86_64.rpm"
    state: latest

